import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { Inter } from "next/font/google";
import { ModalProvider, Modal } from "@/contexts/modal";
import { BurgerMenu } from "@/components/burger-menu";
const inter = Inter({
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`h-screen flex flex-col ${inter.className}`}>
        <nav className=" px-4 py-10 z-50 gap-2 w-screen h-20 flex items-center justify-center fixed">
          <BurgerMenu />
          <Header />
        </nav>

        <ModalProvider>
          <div className="mt-36 h-full">{children}</div>
          <Modal />
        </ModalProvider>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
